server:
  port: 9191

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2

jobs-json-path: /opt/springboot-r4j/catalog-service/src/main/resources/jobs.json      
thread-sleep: 11000